name = "glailwind_merge"
version = "1.1.0"
description = "Utility function to efficiently merge Tailwind CSS classes in JS without style conflicts."
licences = ["MIT"]
repository = { type = "github", user = "dinkelspiel", repo = "glailwind_merge" }

[dependencies]
tails = ">= 0.1.11 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
